version: "3.8"

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./gluetun:/gluetun
      - ./openvpn/<YOUR OVPN FILE>:/gluetun/custom.ovpn:ro
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=<YOUR USER>
      - OPENVPN_PASSWORD=<YOUR PASSWORD>
      - OPENVPN_CUSTOM_CONFIG=/gluetun/custom.ovpn
      - OPENVPN_PROTOCOL=tcp
      - TZ=America/Chicago
      - HTTPPROXY=on
      - HTTPPROXY_LOG=on
      - HTTPPROXY_LISTENING_ADDRESS=:8888
      - FIREWALL_INPUT_PORTS=8888
    networks:
      static_net:
        ipv4_address: 192.168.1.10
    ports:
      - "8888:8888/tcp"
networks:
  static_net:
    external: true